# Generated by Django 5.2.7 on 2025-10-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guest_editor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
